// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkkDE7CD5fLFmzm8LYtPClc84enCwZtYs',
    appId: '1:717485339781:web:c930886c7090128cd565ec',
    messagingSenderId: '717485339781',
    projectId: 'medalert-1a21e',
    authDomain: 'medalert-1a21e.firebaseapp.com',
    storageBucket: 'medalert-1a21e.firebasestorage.app',
    measurementId: 'G-NMYV237FDE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoQGK-PdCwmk5-kVFiHM0-PfDw6rmfDmE',
    appId: '1:717485339781:android:b630625b82e1227dd565ec',
    messagingSenderId: '717485339781',
    projectId: 'medalert-1a21e',
    storageBucket: 'medalert-1a21e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAEWLh7r9GEYzRdIniXR9saHVkz3fbRLI',
    appId: '1:717485339781:ios:a5b679a14c595c9fd565ec',
    messagingSenderId: '717485339781',
    projectId: 'medalert-1a21e',
    storageBucket: 'medalert-1a21e.firebasestorage.app',
    iosBundleId: 'com.example.medalert',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAEWLh7r9GEYzRdIniXR9saHVkz3fbRLI',
    appId: '1:717485339781:ios:a5b679a14c595c9fd565ec',
    messagingSenderId: '717485339781',
    projectId: 'medalert-1a21e',
    storageBucket: 'medalert-1a21e.firebasestorage.app',
    iosBundleId: 'com.example.medalert',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkkDE7CD5fLFmzm8LYtPClc84enCwZtYs',
    appId: '1:717485339781:web:b516bedd04e61f4ad565ec',
    messagingSenderId: '717485339781',
    projectId: 'medalert-1a21e',
    authDomain: 'medalert-1a21e.firebaseapp.com',
    storageBucket: 'medalert-1a21e.firebasestorage.app',
    measurementId: 'G-N6B5295LPS',
  );
}
